site_name: Tellor
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
- Home: 
    - 'About Tellor' : 'index.md'
- Developer Documentation: 
    - 'Deploying Tellor': 'DevDocumentation.md'
    - 'Using Tellor': 'UsingTellor.md'
- Contributors: 'Contributors.md'