site_name: Tellor
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
- Tellor: 
    - 'What is Tellor?' : 'index.md'
- Integrating Tellor into Smart Contracts:
      - 'User Contracts': 'UserSetup.md'
      - 'User Walkthrough': 'UserWalk.md'
- Become a Miner: 
      - 'Miner Implementation': 'MinerSetup.md'
      - 'Miner Walkthrough': 'MinerWalk.md' 
- Data Sources Supported: 'DataSources.md'
- Functions: 
    - 'Deploying Tellor': 'DevDocumentation.md'
    - 'User Functions' : 'UserFunctions.md'
    - 'Miner Functions' : 'MinerFunctions.md'
- Contributors: 'Contributors.md'