site_name: Tellor
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - javascript
        - solidity
nav:
- Tellor: 
    - 'What is Tellor?' : 'index.md'
- Integrate Tellor into  your Smart Contracts:
      - 'User Contracts': 'UserSetup.md'
      - 'User Walkthrough': 'UserWalk.md'
- Become a Miner: 
      - 'Miner Implementation-Non-Technical': 'MinerSetupNonTechnical.md'
      - 'Miner Implementation-Technical':  'MinerSetupTechnical.md'
      - 'Miner Implementation-From Source':  'MinerSetupFromSource.md'
#- Data Sources Supported: 'DataSources.md'
- Creating API for Tellor data: "TellorApi.md"
- Functions: 
    - 'Deploying Tellor': 'DevDocumentation.md'
    - 'User Functions' : 'UserFunctions.md'
    - 'Miner Functions' : 'MinerFunctions.md'
- Contributors: 'Contributors.md'